-- MySQL Script generated by MySQL Workbench
-- Wed Dec 22 18:56:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema control_entrada_salida
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `control_entrada_salida` ;

-- -----------------------------------------------------
-- Schema control_entrada_salida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `control_entrada_salida` DEFAULT CHARACTER SET utf8 ;
USE `control_entrada_salida` ;

-- -----------------------------------------------------
-- Table `control_entrada_salida`.`dispositivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `control_entrada_salida`.`dispositivos` ;

CREATE TABLE IF NOT EXISTS `control_entrada_salida`.`dispositivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `direccionip` VARCHAR(20) NOT NULL,
  `puerto` VARCHAR(5) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `estado` TINYINT NOT NULL,
  `predeterminado` TINYINT NOT NULL,
  `lastimeused` DATETIME NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control_entrada_salida`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `control_entrada_salida`.`empleados` ;

CREATE TABLE IF NOT EXISTS `control_entrada_salida`.`empleados` (
  `documento` VARCHAR(30) NOT NULL,
  `numtarjeta` VARCHAR(20) NOT NULL,
  `nombres` VARCHAR(255) NOT NULL,
  `apellidos` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `estado` ENUM('ACTIVO', 'INACTIVO') NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `modified` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control_entrada_salida`.`entradas_salidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `control_entrada_salida`.`entradas_salidas` ;

CREATE TABLE IF NOT EXISTS `control_entrada_salida`.`entradas_salidas` (
  `num` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `documento` VARCHAR(30) NOT NULL,
  `evento` VARCHAR(255) NOT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`num`, `fecha`, `hora`),
  INDEX `entradas_salidas_dcumento_fk` (`documento` ASC) VISIBLE,
  CONSTRAINT `entradas_salidas_dcumento_fk`
    FOREIGN KEY (`documento`)
    REFERENCES `control_entrada_salida`.`empleados` (`documento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `control_entrada_salida` ;

-- -----------------------------------------------------
-- procedure ELIMINAR_EMPLEADO
-- -----------------------------------------------------

USE `control_entrada_salida`;
DROP procedure IF EXISTS `control_entrada_salida`.`ELIMINAR_EMPLEADO`;

DELIMITER $$
USE `control_entrada_salida`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ELIMINAR_EMPLEADO`(IN doc VARCHAR(30))
BEGIN
	DELETE FROM entradas_salidas WHERE documento = doc;
    DELETE FROM empleados WHERE documento = doc;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
